language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
matrix:
  include:
    # These are the latest Go versions.
    - os: linux
      dist: trusty
      sudo: required
      go: 1.9.x
      script:
        - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install fuse
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install
        - go run build/ci.go test -coverage

    # This builder only tests code linters on latest version of Go
    - os: linux
      dist: trusty
      sudo: required
      go: 1.9.x
      env:
        - lint
      script:
        - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install fuse
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go lint

install:
  - go get golang.org/x/tools/cmd/cover
script:
  - go run build/ci.go install
  - go run build/ci.go test -coverage
